### ISSUE TITLE
about scoring matrix...

### ISSUE THREAD

**Issue by withJack** [webmasterar/libFLASM#1]
Hi, I'm trying to use your program to get the edit distance of two sequences.

I'm having a hard time finding the scoring matrix for the alignment. 
( ex. substitute: 1, in/del: 2 ) 

can you provide the default setting of flasm? 
and perhaps a way to manipulate the scores if available. 
I'm curious about how the error score was calculated

Thank you for your excellent program :) 

+++++++++++++++++++++++++++++++++++
I guess it is commented on the paper..?
"Here we only consider edit distance with unit-cost operations."

does this mean substitue: 1, in/del: 1?

**Comment by webmasterar** [comment]
Hello.

The edit distance model used in libFLASM is a simple one where each mismatch, insertion or deletion increases the error by 1 -- this is what is meant by calling it a unit-cost operation. A match is only reported if the number of errors are less than or equal to the _max_errors_ limit parameter provided to the flasm_ed() function.

The approximate pattern matching algorithm used to calculate this simple edit distance in libFLASM is the fast Myers algorithm as found in the Seqan library. As far as I know, it does not support more complex scoring strategies.

What you can do instead is use the general DPSearch algorithm with SimpleScore and edit line 53 in libflasm.cpp. You can learn more about the options in the Seqan [documentation](https://seqan.readthedocs.io/en/master/Tutorial/Algorithms/PatternMatching/OnlinePatternMatching.html#approximate-search). Please note that performance will not be equivalent to Myers algorithm because the DP algorithm has a different time and space complexity.

I hope that helps... Just to confirm that you are on the right path and using the library as it was intended, are you simply searching for a single pattern in a sequence or are you you searching all factors (substrings) of fixed length from a pattern in the sequence?

Ahmad
